---
- name: Install Apache on localhost (no SSH required)
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  tasks:
    - name: Kill any stuck apt processes
      shell: |
        pkill apt || true
        pkill apt-get || true
        pkill dpkg || true
      changed_when: false
      failed_when: false

    - name: Remove apt lock files if they exist
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/apt/lists/lock
        - /var/cache/apt/archives/lock
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend
      failed_when: false

    - name: Configure dpkg if needed
      command: dpkg --configure -a
      failed_when: false
      changed_when: false

    - name: Clean apt cache
      command: apt clean
      changed_when: false

    - name: Update apt cache with retry (no SSH needed)
      apt:
        update_cache: yes
        cache_valid_time: 0
      retries: 5
      delay: 10
      register: apt_update_result
      until: apt_update_result is succeeded

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create custom index page
      copy:
        dest: /var/www/html/index.html
        content: |
          <h1>Apache Installed Successfully! 🎉</h1>
          <p>Installed on: {{ ansible_facts.hostname }}</p>
          <p>OS: {{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}</p>
          <p>Date: {{ ansible_date_time.date }} {{ ansible_date_time.time }}</p>
          <p>Method: Ansible localhost (no SSH required)</p>
        mode: '0644'

    - name: Display success message
      debug:
        msg: |
          ✅ Apache installation complete!
          🌐 Visit: http://localhost or http://127.0.0.1
          📁 Web root: /var/www/html/
          ⚙️ Config: /etc/apache2/