---
# meta file for motd
galaxy_info:
  author: "Your Name"
  description: "Ansible role for managing Message of the Day (MOTD)"
  license: MIT
  min_ansible_version: 2.9
  
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye

  galaxy_tags:
    - system
    - motd
    - banner
    - security

dependencies: []